name: tarantula_mobile_app
description: "A new Flutter project."
publish_to: 'none' # This package will not be published to pub.dev.

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.3
  intl: ^0.19.0
  flutter_blue: ^0.8.0
  permission_handler: ^11.3.1
  flutter_bluetooth_serial: ^0.4.0

  cupertino_icons: ^1.0.6
  sqflite: any # SQLite veritabanı işlemleri için sqflite paketi eklendi.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/